name: pinecone-upsert-error
dependencies:
  - pip=23.1.2
  - python=3.10.13
  - pip:
    - cohere==4.46
    - langchain==0.1.6
    - langchain_pinecone==0.0.2
    - pinecone-client[grpc]==3.0.2
    - sentence-transformers==2.3.1
